### ISSUE TITLE
Uncaught Error: Call to undefined function ziggeo_p_get_lazyload_activator()

### ISSUE THREAD

**Issue by azanoni** [Ziggeo/ziggeo-wp-video-for-fluent-forms#2]
Hi,

Once you install and try to use this with a Recorder Field, this is the error:

 Fatal error: Uncaught Error: Call to undefined function ziggeo_p_get_lazyload_activator()
in wp-content\plugins\ziggeo-wp-video-for-fluent-forms-master\extend\class-video-recorder.php on line 594

Is calling a function "echo ziggeo_p_get_lazyload_activator();" that didnt exist.

is something that is missing? or need to comment that line?

**Comment by Bane-D** [comment]
Hi Alfredo,

Looks like you did not install the latest version of our core plugin: https://github.com/Ziggeo/ziggeo-wordpress-plugin

You do bring up a good point with your report. We should add a check to the bridge plugins like Fluent Forms one to detect and report instead of causing the error, currently we are just checking that the core plugin is installed.

Can you please try to update to the version 3.0 (only available on Github) and let us know how it goes?

**Comment by azanoni** [comment]
Hi!, 

Sadly we didn't know that the plugin from the official repository https://en-gb.wordpress.org/plugins/ziggeo/ was discontinued (2.1.2 version) , it's an stable version that we could use the 3.x one? are some plans to update soon the official repo?

Anyway, I just downloaded the 3.X version and I didn't see the error, so seems like the 3.X version fix that issue thanks!

I found another js error, but belong to the Ziggeo plugin I'll open a ticket in the other repository.

EDIT: About the bridge that you mention you could use the function [function_exists](https://www.php.net/manual/en/function.function-exists.php)

Thank you for you support.

**Comment by Bane-D** [comment]
Actually it is not discontinued, the Github one is generally more up to date as we push changes there first, then we move it over to WordPress.

As is, there are few more small updates to be done to the core plugin before we will push it to the WordPress repo.

> Anyway, I just downloaded the 3.X version and I didn't see the error, so seems like the 3.X version fix that issue thanks!

Great, thank you. All plugins were recently published to make sure they all work with the lazy load feature that was present in a specific branch of the v2 core plugin and with 3.0 it is part of it.

> I found another js error, but belong to the Ziggeo plugin I'll open a ticket in the other repository.

> EDIT: About the bridge that you mention you could use the function [function_exists](https://www.php.net/manual/en/function.function-exists.php)

Great, thank you. Will be checking the error report out. In regards to the function check, you are correct, we use that in some places in our plugin to allow override however can be used in checking as well. In this case it was more about forgetting to add the check as the plugins were updated.

Since the error is no longer happening I will close the issue, however please do reach out if you have any additional questions.
